name: Release

on:
  release:
    types: [created]

jobs:
  publish-cli:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: macos-12
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "::set-output name=release_version::$RELEASE_VERSION"
      - name: Android setup
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile binaries
        run: |
          echo $ANDROID_NDK_HOME
          ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/
          chmod +x ./hack/build.sh
          ./hack/build.sh
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.release_version }}
      - name: Save release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
